spring:
 cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: payment-route
            uri: lb://payment-service
            predicates:
            - Path=/paymentservice/api/v1/payments/**
        
server:
  port: 9090
  
