spring:
 cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: payment-route
            uri: lb://payment-service
            predicates:
            - Path=/payments/**
            filters:
            - RewritePath=/payments/(?<segment>.*), /paymentservice/api/v1/payments/${segment}
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payment
            
          - id: product-route
            uri: lb://product-service
            predicates:
            - Path=/products/**
            filters:
            - RewritePath=/products/(?<segment>.*), /pms/api/v1/products/${segment}
            - name: CircuitBreaker
              args:
                name: productCircuitBreaker
                fallbackUri: forward:/fallback/product
          
          - id: order-route
            uri: lb://order-service
            predicates:
            - Path=/orders/**
            filters:
            - RewritePath=/orders/?(?<segment>.*), /oms/api/v1/orders${segment}
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/order
        
server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        
  tracing:
    sampling:
      probability: 1.0
  
  
