spring:
 cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: payment-route
            uri: lb://payment-service
            predicates:
            - Path=/payments/**
            filters:
            - RewritePath=/payments/(?<segment>.*), /paymentservice/api/v1/payments/${segment}
        
server:
  port: 9090
  
