spring:   
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    
    username: root
    
    password: sreen123

management:
  endpoints:
    web:
      exposure:
        include: refresh

  tracing:
    sampling:
      probability: 1.0
    
server:
  port: 8085
  
  servlet:
    context-path: /paymentservice
    
